# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yt_downloader_gui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(391, 305)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.url_box = QtWidgets.QLineEdit(self.centralwidget)
        self.url_box.setGeometry(QtCore.QRect(54, 11, 331, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.url_box.sizePolicy().hasHeightForWidth())
        self.url_box.setSizePolicy(sizePolicy)
        self.url_box.setObjectName("url_box")
        self.url_text = QtWidgets.QLabel(self.centralwidget)
        self.url_text.setGeometry(QtCore.QRect(11, 11, 36, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.url_text.setFont(font)
        self.url_text.setObjectName("url_text")
        self.is_playlist_check = QtWidgets.QCheckBox(self.centralwidget)
        self.is_playlist_check.setGeometry(QtCore.QRect(250, 50, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.is_playlist_check.setFont(font)
        self.is_playlist_check.setObjectName("is_playlist_check")
        self.download_button = QtWidgets.QPushButton(self.centralwidget)
        self.download_button.setEnabled(False)
        self.download_button.setGeometry(QtCore.QRect(10, 130, 371, 28))
        self.download_button.setObjectName("download_button")
        self.custom_dir_name_check = QtWidgets.QCheckBox(self.centralwidget)
        self.custom_dir_name_check.setGeometry(QtCore.QRect(10, 90, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.custom_dir_name_check.setFont(font)
        self.custom_dir_name_check.setObjectName("custom_dir_name_check")
        self.custom_dir_name_box = QtWidgets.QLineEdit(self.centralwidget)
        self.custom_dir_name_box.setEnabled(False)
        self.custom_dir_name_box.setGeometry(QtCore.QRect(160, 90, 221, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.custom_dir_name_box.sizePolicy().hasHeightForWidth())
        self.custom_dir_name_box.setSizePolicy(sizePolicy)
        self.custom_dir_name_box.setReadOnly(False)
        self.custom_dir_name_box.setObjectName("custom_dir_name_box")
        self.curr_download_line = QtWidgets.QLabel(self.centralwidget)
        self.curr_download_line.setGeometry(QtCore.QRect(10, 170, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.curr_download_line.setFont(font)
        self.curr_download_line.setObjectName("curr_download_line")
        self.curr_download_text = QtWidgets.QLabel(self.centralwidget)
        self.curr_download_text.setGeometry(QtCore.QRect(140, 170, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.curr_download_text.setFont(font)
        self.curr_download_text.setObjectName("curr_download_text")
        self.progress_line = QtWidgets.QLabel(self.centralwidget)
        self.progress_line.setGeometry(QtCore.QRect(10, 200, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.progress_line.setFont(font)
        self.progress_line.setObjectName("progress_line")
        self.progress_text = QtWidgets.QLabel(self.centralwidget)
        self.progress_text.setGeometry(QtCore.QRect(150, 200, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.progress_text.setFont(font)
        self.progress_text.setObjectName("progress_text")
        self.status_line = QtWidgets.QLabel(self.centralwidget)
        self.status_line.setGeometry(QtCore.QRect(10, 230, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.status_line.setFont(font)
        self.status_line.setObjectName("status_line")
        self.status_text = QtWidgets.QLabel(self.centralwidget)
        self.status_text.setGeometry(QtCore.QRect(100, 230, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.status_text.setFont(font)
        self.status_text.setText("")
        self.status_text.setObjectName("status_text")
        self.download_settings_text = QtWidgets.QLabel(self.centralwidget)
        self.download_settings_text.setGeometry(QtCore.QRect(10, 50, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.download_settings_text.setFont(font)
        self.download_settings_text.setObjectName("download_settings_text")
        self.download_setting_option = QtWidgets.QComboBox(self.centralwidget)
        self.download_setting_option.setGeometry(QtCore.QRect(150, 50, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.download_setting_option.setFont(font)
        self.download_setting_option.setObjectName("download_setting_option")
        self.download_setting_option.addItem("")
        self.download_setting_option.addItem("")
        self.download_setting_option.addItem("")
        self.download_setting_option.addItem("")
        self.download_setting_option.addItem("")
        self.download_setting_option.addItem("")
        self.download_setting_option.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 391, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.download_setting_option.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.url_text.setText(_translate("MainWindow", "URL: "))
        self.is_playlist_check.setText(_translate("MainWindow", "Playlist Download"))
        self.download_button.setText(_translate("MainWindow", "Download"))
        self.custom_dir_name_check.setText(_translate("MainWindow", "Custom Dir Name"))
        self.curr_download_line.setText(_translate("MainWindow", "Current Download:"))
        self.curr_download_text.setText(_translate("MainWindow", "None"))
        self.progress_line.setText(_translate("MainWindow", "Download Progress:"))
        self.progress_text.setText(_translate("MainWindow", "0 %"))
        self.status_line.setText(_translate("MainWindow", "Warning List:"))
        self.download_settings_text.setText(_translate("MainWindow", "Download Settings:"))
        self.download_setting_option.setItemText(0, _translate("MainWindow", "144p"))
        self.download_setting_option.setItemText(1, _translate("MainWindow", "240p"))
        self.download_setting_option.setItemText(2, _translate("MainWindow", "360p"))
        self.download_setting_option.setItemText(3, _translate("MainWindow", "480p"))
        self.download_setting_option.setItemText(4, _translate("MainWindow", "720p"))
        self.download_setting_option.setItemText(5, _translate("MainWindow", "1080p"))
        self.download_setting_option.setItemText(6, _translate("MainWindow", "audio"))
